POST http://localhost:3000/user
content-type: application/json

{
    "name": "usuario1",
    "email": "usuario1@gmail.com",
    "password": "12345"
}

###
PATCH  http://localhost:3000/user/1
content-type: application/json

{
    "name": "usuario1",
    "email": "usuario1@gmail.com"
}


###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/1

###
DELETE http://localhost:3000/user/5